In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
train.shape

(891, 12)

In [7]:
test.shape

(418, 11)

## Missing value
Info method gives all the details about columns, therefore we can identify how many missing value persent in the intire entries. 


In [8]:
train.info() 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [9]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [10]:
# Here we see in the train dataset in Cabine column there is only 204 non-null value persent in the 891 total entries. 

In [11]:
#Therefore we can drop these column

In [12]:
#train.drop([columns='Cabine']) #Since it not permanant operation therefore we use inplace==true

In [13]:
train.drop(columns=['Cabin'], inplace=True)

In [14]:
test.drop(columns=['Cabin'], inplace=True)

In [15]:
train.isnull() # Gives boolian value True or false, If there is null value than gives Ture otherwise gives false

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Embarked  
0    False     False  
1    False     False  
2    False     False  
3    False     False  
4    False     False  
..     ...       ...  
886  False     False  
887  False     False  
888  False     False  
889  False     False  
890  False     False  

[891 rows x 11 columns]

In [16]:
# To see how many null value persent in the intire column we can write

In [17]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [18]:
test.isnull().sum()

PassengerId     0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            1
Embarked        0
dtype: int64

# Identify which city passanger is traveling more

In [19]:
train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [20]:
# Here we see more people are going to S ie 644 (Therefore We can fill the na or Misssing values with the S)

In [21]:
# We know there are 2 missing value in the Embarked Column. Replace the missing value with S

In [22]:
train['Embarked'].fillna('S')

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [23]:
#Since this is not permanant. For the permanant we can write inplace = True

In [24]:
train['Embarked'].fillna('S',inplace = True)

In [25]:
train['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [26]:
train.isnull().sum()   

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [27]:
 # Here we see there is no missing value in the Embarked column
# But in the Age column 177 missing value persent

In [28]:
#On the above test set we saw that 1 missing value was present in the Fare column.
# Now handle this missing value by replacing mean value

In [29]:
test['Fare'].fillna(test['Fare'].mean(), inplace = True)
test.isnull().sum()

PassengerId     0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            0
Embarked        0
dtype: int64

In [30]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

In [31]:
#Since 177 value misiing in age column in train dataset.
# if we see the percentage 

In [32]:
(177/891)*100

19.865319865319865

In [33]:
# Here we see 19% values are missing. If we delete the Age column in train dataset then we have to delete 19% rows. 
#If there are 1cr data find dely and remove  19% of data that is too much, Therefore we shouldn't remove it.
# Then what we have to do
#        Now generate 177 random value

In [34]:
np.random.randint(train['Age'].mean()-train['Age'].std(),train['Age'].mean()+train['Age'].std(),177)

array([25, 36, 18, 31, 36, 41, 40, 41, 16, 21, 26, 18, 42, 17, 30, 38, 28,
       37, 43, 40, 19, 32, 38, 26, 34, 21, 42, 21, 31, 29, 34, 40, 24, 33,
       36, 24, 24, 37, 24, 39, 33, 28, 22, 34, 24, 36, 40, 34, 22, 43, 19,
       31, 38, 32, 23, 25, 17, 18, 34, 32, 17, 31, 22, 39, 40, 38, 41, 33,
       24, 43, 16, 27, 37, 34, 21, 20, 42, 41, 34, 23, 28, 33, 38, 19, 25,
       37, 28, 31, 41, 21, 30, 20, 23, 41, 33, 23, 28, 38, 19, 19, 18, 27,
       33, 23, 41, 41, 22, 21, 35, 16, 34, 27, 42, 22, 40, 40, 19, 20, 21,
       18, 38, 32, 17, 25, 19, 33, 26, 42, 25, 21, 36, 15, 32, 40, 20, 23,
       36, 16, 34, 41, 42, 32, 36, 29, 27, 35, 40, 21, 31, 26, 20, 38, 18,
       37, 31, 38, 38, 40, 19, 38, 20, 37, 29, 23, 41, 41, 29, 32, 42, 41,
       43, 15, 23, 19, 35, 16, 39])

In [35]:
#Now store this value in train_age variable

In [36]:
train_age=np.random.randint(train['Age'].mean()-train['Age'].std(),train['Age'].mean()+train['Age'].std(),177)

In [37]:
#train_age
train_age

array([23, 29, 42, 37, 18, 24, 41, 39, 23, 25, 18, 42, 33, 32, 15, 29, 22,
       33, 32, 40, 16, 39, 30, 28, 15, 33, 23, 29, 21, 43, 26, 43, 32, 24,
       20, 20, 18, 25, 42, 15, 15, 40, 42, 19, 24, 40, 21, 20, 38, 20, 18,
       33, 28, 17, 18, 15, 33, 23, 33, 36, 28, 21, 26, 19, 23, 39, 37, 28,
       23, 27, 30, 36, 32, 43, 27, 40, 22, 18, 22, 22, 32, 36, 27, 28, 15,
       30, 29, 41, 36, 35, 31, 26, 42, 20, 38, 43, 31, 37, 40, 39, 32, 23,
       16, 38, 25, 38, 38, 21, 26, 36, 38, 19, 20, 21, 26, 38, 37, 18, 22,
       31, 25, 37, 30, 43, 41, 17, 41, 36, 31, 27, 25, 16, 17, 26, 27, 24,
       21, 39, 23, 40, 19, 25, 28, 40, 23, 20, 43, 32, 28, 16, 18, 38, 43,
       18, 42, 29, 43, 41, 37, 35, 35, 36, 42, 25, 36, 24, 33, 15, 33, 36,
       23, 43, 28, 29, 22, 24, 35])

In [38]:
# Similarlly do the same with the test dataset

In [39]:
test_age=np.random.randint(test['Age'].mean()-train['Age'].std(),test['Age'].mean()+train['Age'].std(),86)

In [40]:
test_age

array([27, 20, 25, 28, 35, 23, 16, 40, 39, 42, 20, 23, 18, 17, 35, 20, 30,
       43, 19, 17, 39, 39, 23, 23, 21, 15, 24, 34, 17, 43, 21, 40, 28, 34,
       17, 23, 16, 24, 17, 28, 35, 15, 42, 40, 29, 18, 27, 25, 25, 34, 19,
       38, 23, 42, 22, 15, 19, 31, 35, 40, 21, 19, 16, 29, 33, 20, 39, 29,
       15, 36, 23, 26, 24, 30, 27, 26, 16, 29, 42, 27, 29, 40, 29, 21, 28,
       41])

In [41]:
# Now see the null value in Age column in train data set

In [42]:
train['Age'].isnull() 

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [43]:
train['Age'].shape

(891,)

In [44]:
#Here we see 891 rows but we need 177 rows
# We can do this by mapping

In [45]:
train['Age'][train['Age'].isnull()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
       ..
859   NaN
863   NaN
868   NaN
878   NaN
888   NaN
Name: Age, Length: 177, dtype: float64

In [46]:
train['Age'][train['Age'].isnull()].shape

(177,)

In [47]:
# All 177 values are Nan
# Now replace this nan value train_age

In [48]:
train['Age'][train['Age'].isnull()]=train_age

/tmp/ipykernel_2792/4268069075.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Age'][train['Age'].isnull()]=train_age


In [49]:
# This is not an error, It is showing a warning, bacically saying its seting a copy which   
# which is not all dataframe 
# but its some part of the dataframe

In [50]:
train.isnull().sum() #To see oll the null value 

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [51]:
test['Age'][test['Age'].isnull()]=test_age

/tmp/ipykernel_2792/3484201817.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Age'][test['Age'].isnull()]=test_age


In [52]:
test.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [53]:
# Above we see there is no missing value in any column in test or train dataset

# Data analysis process:

1 - Asking the right question

2 - Data preprocessing

3 - Exploratory Data Analysis(EDA)

4 - Confine Conclusion

5 - Convey Result

## 1 & 2 stepe we have done

## EDA